In [1]:
import requests
from datetime import datetime, timedelta, date
import pandas as pd
# contract_url_old = 'https://raw.githubusercontent.com/element-fi/elf-deploy/8a8a92b79622edfa35c1341859f7b125ab69e37b/addresses/mainnet.json'
# element_token_mappings_old = requests.get(contract_url_old).json()
contract_url = 'https://raw.githubusercontent.com/element-fi/elf-deploy/main/addresses/mainnet.json'
element_token_mappings = requests.get(contract_url).json()

In [2]:
tokens = []
# display(element_token_mappings)
for token, data in element_token_mappings['tranches'].items():
    for tranche in data:
        # display(tranche)
        tokens.append({
            'expiry_timestamp': tranche['expiration'],
            'expiry_datetime': datetime.fromtimestamp(tranche['expiration']).strftime('%Y-%m-%d %H:%M:%S'),
            'token_address_raw': '\\'+tranche['address'][1:].lower(),
            'token':token,
            'token_type': 'pToken'
        })
        for token_type in ('ptPool', 'ytPool'):
            if token_type in tranche:
                tokens.append({
                    'expiry_timestamp': tranche['expiration'],
                    'expiry_datetime': datetime.fromtimestamp(tranche['expiration']).strftime('%Y-%m-%d %H:%M:%S'),
                    'short_date': datetime.fromtimestamp(tranche['expiration']).strftime('%d%b%Y'),
                    'token_address_raw': '\\'+tranche[token_type]['address'][1:].lower(),
                    'token':token,
                    'token_type': token_type,
                    'poolId': '\\'+tranche[token_type]['poolId'][1:].lower()
                })
tokens = pd.DataFrame(tokens)
# display(tokens.loc[(tokens.token=='alusd3crv-f') & (tokens.token_type=='pToken'),:])
print('live terms:')
display(tokens.loc[(tokens.expiry_timestamp.values > datetime.now().timestamp()),:])

live terms:

,expiry_timestamp,expiry_datetime,token_address_raw,token,token_type,short_date,poolId
30,1677243924,2023-02-24 08:05:24,\x09459654777bb2669ad8ad0b54e876d4b5ff77f4,dai,pToken,NaN,NaN
31,1677243924,2023-02-24 08:05:24,\x7f4a33dee068c4fa012d64677c61519a578dfa35,dai,ptPool,24Feb2023,\x7f4a33dee068c4fa012d64677c61519a578dfa350002...
63,1677243924,2023-02-24 08:05:24,\x724e3073317d4b1a8d0c6e89b137ea5af1f4051e,stecrv,pToken,NaN,NaN
64,1677243924,2023-02-24 08:05:24,\x07f589ea6b789249c83992dd1ed324c3b80fd06b,stecrv,ptPool,24Feb2023,\x07f589ea6b789249c83992dd1ed324c3b80fd06b0002...
79,1677243756,2023-02-24 08:02:36,\xb83809806a076a1413437ea3e553d6bf41993a21,usdc,pToken,NaN,NaN
80,1677243756,2023-02-24 08:02:36,\x5746afd392b13946aacbda40317751db27d8b918,usdc,ptPool,24Feb2023,\x5746afd392b13946aacbda40317751db27d8b9180002...

In [3]:
display(tokens.loc[(tokens.token.values == 'usdc'),:])

,expiry_timestamp,expiry_datetime,token_address_raw,token,token_type,short_date,poolId
65,1635528110,2021-10-29 13:21:50,\xf38c3e836be9cd35072055ff6a9ba570e0b70797,usdc,pToken,NaN,NaN
66,1635528110,2021-10-29 13:21:50,\x787546bf2c05e3e19e2b6bde57a203da7f682eff,usdc,ptPool,29Oct2021,\x787546bf2c05e3e19e2b6bde57a203da7f682eff0002...
67,1635528110,2021-10-29 13:21:50,\x2d6e3515c8b47192ca3913770fa741d3c4dac354,usdc,ytPool,29Oct2021,\x2d6e3515c8b47192ca3913770fa741d3c4dac3540002...
68,1643382476,2022-01-28 10:07:56,\x8a2228705ec979961f0e16df311debcf097a2766,usdc,pToken,NaN,NaN
69,1643382476,2022-01-28 10:07:56,\x10a2f8bd81ee2898d7ed18fb8f114034a549fa59,usdc,ptPool,28Jan2022,\x10a2f8bd81ee2898d7ed18fb8f114034a549fa590002...
70,1643382476,2022-01-28 10:07:56,\x9e030b67a8384cbba09d5927533aa98010c87d91,usdc,ytPool,28Jan2022,\x9e030b67a8384cbba09d5927533aa98010c87d910002...
71,1639727861,2021-12-17 02:57:41,\x76a34d72b9cf97d972fb0e390eb053a37f211c74,usdc,pToken,NaN,NaN
72,1639727861,2021-12-17 02:57:41,\x90ca5cef5b29342b229fb8ae2db5d8f4f894d652,usdc,ptPool,17Dec2021,\x90ca5cef5b29342b229fb8ae2db5d8f4f894d6520002...
73,1639727861,2021-12-17 02:57:41,\x7c9cf12d783821d5c63d8e9427af5c44bad92445,usdc,ytPool,17Dec2021,\x7c9cf12d783821d5c63d8e9427af5c44bad924450002...
74,1651253068,2022-04-29 13:24:28,\x52c9886d5d87b0f06ebacbeff750b5ffad5d17d9,usdc,pToken,NaN,NaN
75,1651253068,2022-04-29 13:24:28,\x7edde0cb05ed19e03a9a47cd5e53fc57fde1c80c,usdc,ptPool,29Apr2022,\x7edde0cb05ed19e03a9a47cd5e53fc57fde1c80c0002...
76,1651253068,2022-04-29 13:24:28,\x7173b184525fead2ffbde5fbe6fcb65ea8246ee7,usdc,ytPool,29Apr2022,\x7173b184525fead2ffbde5fbe6fcb65ea8246ee70002...
77,1663355860,2022-09-16 15:17:40,\xcfe60a1535ecc5b0bc628dc97111c8bb01637911,usdc,pToken,NaN,NaN
78,1663355860,2022-09-16 15:17:40,\x56df5ef1a0a86c2a5dd9cc001aa8152545bdbdec,usdc,ptPool,16Sep2022,\x56df5ef1a0a86c2a5dd9cc001aa8152545bdbdec0002...
79,1677243756,2023-02-24 08:02:36,\xb83809806a076a1413437ea3e553d6bf41993a21,usdc,pToken,NaN,NaN
80,1677243756,2023-02-24 08:02:36,\x5746afd392b13946aacbda40317751db27d8b918,usdc,ptPool,24Feb2023,\x5746afd392b13946aacbda40317751db27d8b9180002...

In [4]:
[i for i in tokens.loc[tokens.token_type=='ptPool','poolId'].values]
q='\''+'\',\''.join(tokens.loc[tokens.token_type=='ptPool','poolId'])+'\''
print(q)

'\xc9ad279994980f8df348b526901006972509677f00020000000000000000009e','\x63e9b50dd3eb63bfbf93b26f57b9efb574e595760002000000000000000000cf','\x13cf9e8115f35828a26062b6c05a56c72f54e0c60002000000000000000001d9','\xf6dc4640d2783654bef88e0df3fb0f051f0dfc1a00020000000000000000007e','\x6dd0f7c8f4793ed2531c0df4fea8633a21fdcff40002000000000000000000b7','\xc80fef22fccc277ac0ffea84d111888a767f717e0002000000000000000001b1','\x3a693eb97b500008d4bb6258906f7bbca1d09cc5000200000000000000000065','\x71628c66c502f988fbb9e17081f2bd14e361faf4000200000000000000000078','\xa47d1251cf21ad42685cc6b8b3a186a73dbd06cf000200000000000000000097','\xedf085f65b4f6c155e13155502ef925c9a756003000200000000000000000123','\x8ffd1dc7c3ef65f833cf84dbcd15b6ad7f9c54ec000200000000000000000199','\x7f4a33dee068c4fa012d64677c61519a578dfa35000200000000000000000346','\x6ac02ecd0c2a23b11f9afb3b3aaf237169475cac0002000000000000000000a8','\xa8d4433badaa1a35506804b43657b0694dea928d00020000000000000000005e','\x893b30574bf183d69413717f30b17062ec9dfd8b000200000000000000000061','\x56f30398d13f111401d6e7ffe758254a0946687d000200000000000000000105','\x489eedb33f82574afeabb3f4e156fbf662308ada0002000000000000000001a3','\x09b1b33bad0e87454ff05696b1151bfbd208a43f0002000000000000000000a6','\x14792d3f6fcf2661795d1e08ef818bf612708bbf0002000000000000000000be','\xce16e7ed7654a3453e8faf748f2c82e57069278f00020000000000000000006d','\x544c823194218f0640dae8291c1f59752d25fae3000200000000000000000093','\xb03c6b351a283bc1cd26b9cf6d7b0c4556013bdb0002000000000000000000ab','\xabb93e3787b984cb62dcd962af8732f52ff57586000200000000000000000183','\x07f589ea6b789249c83992dd1ed324c3b80fd06b00020000000000000000034e','\x787546bf2c05e3e19e2b6bde57a203da7f682eff00020000000000000000007c','\x10a2f8bd81ee2898d7ed18fb8f114034a549fa59000200000000000000000090','\x90ca5cef5b29342b229fb8ae2db5d8f4f894d6520002000000000000000000b5','\x7edde0cb05ed19e03a9a47cd5e53fc57fde1c80c0002000000000000000000c8','\x56df5ef1a0a86c2a5dd9cc001aa8152545bdbdec000200000000000000000168','\x5746afd392b13946aacbda40317751db27d8b91800020000000000000000034c','\x4db9024fc9f477134e00da0da3c77de98d9836ac000200000000000000000086','\x4bd6d86debdb9f5413e631ad386c4427dc9d01b20002000000000000000000ec'

In [5]:
case_string = "CASE "
for i in tokens.loc[tokens.token_type=='ptPool',['poolId','token','short_date']].itertuples(index=False):
    case_string += f"WHEN bv.\"poolId\" = '{i.poolId}' THEN '{i.token}-{i.short_date}' "
case_string += "END"
print('poolname:')
print(case_string)

poolname:
CASE WHEN bv."poolId" = '\xc9ad279994980f8df348b526901006972509677f00020000000000000000009e' THEN 'alusd3crv-f-28Jan2022' WHEN bv."poolId" = '\x63e9b50dd3eb63bfbf93b26f57b9efb574e595760002000000000000000000cf' THEN 'alusd3crv-f-29Apr2022' WHEN bv."poolId" = '\x13cf9e8115f35828a26062b6c05a56c72f54e0c60002000000000000000001d9' THEN 'alusd3crv-f-16Sep2022' WHEN bv."poolId" = '\xf6dc4640d2783654bef88e0df3fb0f051f0dfc1a00020000000000000000007e' THEN 'crv3crypto-12Nov2021' WHEN bv."poolId" = '\x6dd0f7c8f4793ed2531c0df4fea8633a21fdcff40002000000000000000000b7' THEN 'crv3crypto-29Apr2022' WHEN bv."poolId" = '\xc80fef22fccc277ac0ffea84d111888a767f717e0002000000000000000001b1' THEN 'crv3crypto-16Sep2022' WHEN bv."poolId" = '\x3a693eb97b500008d4bb6258906f7bbca1d09cc5000200000000000000000065' THEN 'crvtricrypto-14Aug2021' WHEN bv."poolId" = '\x71628c66c502f988fbb9e17081f2bd14e361faf4000200000000000000000078' THEN 'dai-15Oct2021' WHEN bv."poolId" = '\xa47d1251cf21ad42685cc6b8b3a186a73dbd06cf000200000000000000000097' THEN 'dai-28Jan2022' WHEN bv."poolId" = '\xedf085f65b4f6c155e13155502ef925c9a756003000200000000000000000123' THEN 'dai-29Apr2022' WHEN bv."poolId" = '\x8ffd1dc7c3ef65f833cf84dbcd15b6ad7f9c54ec000200000000000000000199' THEN 'dai-16Sep2022' WHEN bv."poolId" = '\x7f4a33dee068c4fa012d64677c61519a578dfa35000200000000000000000346' THEN 'dai-24Feb2023' WHEN bv."poolId" = '\x6ac02ecd0c2a23b11f9afb3b3aaf237169475cac0002000000000000000000a8' THEN 'eurscrv-11Feb2022' WHEN bv."poolId" = '\xa8d4433badaa1a35506804b43657b0694dea928d00020000000000000000005e' THEN 'lusd3crv-f-28Sep2021' WHEN bv."poolId" = '\x893b30574bf183d69413717f30b17062ec9dfd8b000200000000000000000061' THEN 'lusd3crv-f-27Dec2021' WHEN bv."poolId" = '\x56f30398d13f111401d6e7ffe758254a0946687d000200000000000000000105' THEN 'lusd3crv-f-29Apr2022' WHEN bv."poolId" = '\x489eedb33f82574afeabb3f4e156fbf662308ada0002000000000000000001a3' THEN 'lusd3crv-f-16Sep2022' WHEN bv."poolId" = '\x09b1b33bad0e87454ff05696b1151bfbd208a43f0002000000000000000000a6' THEN 'mim-3lp3crv-f-11Feb2022' WHEN bv."poolId" = '\x14792d3f6fcf2661795d1e08ef818bf612708bbf0002000000000000000000be' THEN 'mim-3lp3crv-f-29Apr2022' WHEN bv."poolId" = '\xce16e7ed7654a3453e8faf748f2c82e57069278f00020000000000000000006d' THEN 'stecrv-15Oct2021' WHEN bv."poolId" = '\x544c823194218f0640dae8291c1f59752d25fae3000200000000000000000093' THEN 'stecrv-28Jan2022' WHEN bv."poolId" = '\xb03c6b351a283bc1cd26b9cf6d7b0c4556013bdb0002000000000000000000ab' THEN 'stecrv-15Apr2022' WHEN bv."poolId" = '\xabb93e3787b984cb62dcd962af8732f52ff57586000200000000000000000183' THEN 'stecrv-16Sep2022' WHEN bv."poolId" = '\x07f589ea6b789249c83992dd1ed324c3b80fd06b00020000000000000000034e' THEN 'stecrv-24Feb2023' WHEN bv."poolId" = '\x787546bf2c05e3e19e2b6bde57a203da7f682eff00020000000000000000007c' THEN 'usdc-29Oct2021' WHEN bv."poolId" = '\x10a2f8bd81ee2898d7ed18fb8f114034a549fa59000200000000000000000090' THEN 'usdc-28Jan2022' WHEN bv."poolId" = '\x90ca5cef5b29342b229fb8ae2db5d8f4f894d6520002000000000000000000b5' THEN 'usdc-17Dec2021' WHEN bv."poolId" = '\x7edde0cb05ed19e03a9a47cd5e53fc57fde1c80c0002000000000000000000c8' THEN 'usdc-29Apr2022' WHEN bv."poolId" = '\x56df5ef1a0a86c2a5dd9cc001aa8152545bdbdec000200000000000000000168' THEN 'usdc-16Sep2022' WHEN bv."poolId" = '\x5746afd392b13946aacbda40317751db27d8b91800020000000000000000034c' THEN 'usdc-24Feb2023' WHEN bv."poolId" = '\x4db9024fc9f477134e00da0da3c77de98d9836ac000200000000000000000086' THEN 'wbtc-26Nov2021' WHEN bv."poolId" = '\x4bd6d86debdb9f5413e631ad386c4427dc9d01b20002000000000000000000ec' THEN 'wbtc-29Apr2022' END

In [6]:
case_string = "CASE "
for i in tokens.loc[tokens.token_type=='ptPool',['poolId','expiry_timestamp']].itertuples(index=False):
    case_string += f"WHEN bv.\"poolId\" = '{i.poolId}' THEN to_timestamp({i.expiry_timestamp}) "
case_string += "END"
print('expiry:')
print(case_string)

expiry:
CASE WHEN bv."poolId" = '\xc9ad279994980f8df348b526901006972509677f00020000000000000000009e' THEN to_timestamp(1643382460) WHEN bv."poolId" = '\x63e9b50dd3eb63bfbf93b26f57b9efb574e595760002000000000000000000cf' THEN to_timestamp(1651267340) WHEN bv."poolId" = '\x13cf9e8115f35828a26062b6c05a56c72f54e0c60002000000000000000001d9' THEN to_timestamp(1663336829) WHEN bv."poolId" = '\xf6dc4640d2783654bef88e0df3fb0f051f0dfc1a00020000000000000000007e' THEN to_timestamp(1636746083) WHEN bv."poolId" = '\x6dd0f7c8f4793ed2531c0df4fea8633a21fdcff40002000000000000000000b7' THEN to_timestamp(1651240496) WHEN bv."poolId" = '\xc80fef22fccc277ac0ffea84d111888a767f717e0002000000000000000001b1' THEN to_timestamp(1663354791) WHEN bv."poolId" = '\x3a693eb97b500008d4bb6258906f7bbca1d09cc5000200000000000000000065' THEN to_timestamp(1628997564) WHEN bv."poolId" = '\x71628c66c502f988fbb9e17081f2bd14e361faf4000200000000000000000078' THEN to_timestamp(1634346845) WHEN bv."poolId" = '\xa47d1251cf21ad42685cc6b8b3a186a73dbd06cf000200000000000000000097' THEN to_timestamp(1643382446) WHEN bv."poolId" = '\xedf085f65b4f6c155e13155502ef925c9a756003000200000000000000000123' THEN to_timestamp(1651275535) WHEN bv."poolId" = '\x8ffd1dc7c3ef65f833cf84dbcd15b6ad7f9c54ec000200000000000000000199' THEN to_timestamp(1663361092) WHEN bv."poolId" = '\x7f4a33dee068c4fa012d64677c61519a578dfa35000200000000000000000346' THEN to_timestamp(1677243924) WHEN bv."poolId" = '\x6ac02ecd0c2a23b11f9afb3b3aaf237169475cac0002000000000000000000a8' THEN to_timestamp(1644604852) WHEN bv."poolId" = '\xa8d4433badaa1a35506804b43657b0694dea928d00020000000000000000005e' THEN to_timestamp(1632834462) WHEN bv."poolId" = '\x893b30574bf183d69413717f30b17062ec9dfd8b000200000000000000000061' THEN to_timestamp(1640620258) WHEN bv."poolId" = '\x56f30398d13f111401d6e7ffe758254a0946687d000200000000000000000105' THEN to_timestamp(1651264326) WHEN bv."poolId" = '\x489eedb33f82574afeabb3f4e156fbf662308ada0002000000000000000001a3' THEN to_timestamp(1663348630) WHEN bv."poolId" = '\x09b1b33bad0e87454ff05696b1151bfbd208a43f0002000000000000000000a6' THEN to_timestamp(1644601070) WHEN bv."poolId" = '\x14792d3f6fcf2661795d1e08ef818bf612708bbf0002000000000000000000be' THEN to_timestamp(1651247155) WHEN bv."poolId" = '\xce16e7ed7654a3453e8faf748f2c82e57069278f00020000000000000000006d' THEN to_timestamp(1634325622) WHEN bv."poolId" = '\x544c823194218f0640dae8291c1f59752d25fae3000200000000000000000093' THEN to_timestamp(1643382514) WHEN bv."poolId" = '\xb03c6b351a283bc1cd26b9cf6d7b0c4556013bdb0002000000000000000000ab' THEN to_timestamp(1650025565) WHEN bv."poolId" = '\xabb93e3787b984cb62dcd962af8732f52ff57586000200000000000000000183' THEN to_timestamp(1663341022) WHEN bv."poolId" = '\x07f589ea6b789249c83992dd1ed324c3b80fd06b00020000000000000000034e' THEN to_timestamp(1677243924) WHEN bv."poolId" = '\x787546bf2c05e3e19e2b6bde57a203da7f682eff00020000000000000000007c' THEN to_timestamp(1635528110) WHEN bv."poolId" = '\x10a2f8bd81ee2898d7ed18fb8f114034a549fa59000200000000000000000090' THEN to_timestamp(1643382476) WHEN bv."poolId" = '\x90ca5cef5b29342b229fb8ae2db5d8f4f894d6520002000000000000000000b5' THEN to_timestamp(1639727861) WHEN bv."poolId" = '\x7edde0cb05ed19e03a9a47cd5e53fc57fde1c80c0002000000000000000000c8' THEN to_timestamp(1651253068) WHEN bv."poolId" = '\x56df5ef1a0a86c2a5dd9cc001aa8152545bdbdec000200000000000000000168' THEN to_timestamp(1663355860) WHEN bv."poolId" = '\x5746afd392b13946aacbda40317751db27d8b91800020000000000000000034c' THEN to_timestamp(1677243756) WHEN bv."poolId" = '\x4db9024fc9f477134e00da0da3c77de98d9836ac000200000000000000000086' THEN to_timestamp(1637941844) WHEN bv."poolId" = '\x4bd6d86debdb9f5413e631ad386c4427dc9d01b20002000000000000000000ec' THEN to_timestamp(1651265241) END

In [7]:
wrappedTokens = []
# display(element_token_mappings['wrappedPositions'])
for version in element_token_mappings['wrappedPositions'].keys():
    for wrapperType,data in element_token_mappings['wrappedPositions'][version].items():
        for token,address in data.items():
            if wrapperType=='yearnv4':
                wrappedTokens.append((version,token+'v4',address))
            else:
                wrappedTokens.append((version,token,address))
wrappedTokens = pd.DataFrame(wrappedTokens,columns={'version','token','address'})
display(wrappedTokens.style.hide_index())

In [8]:
vaults = []
for vaultType,data in element_token_mappings['vaults'].items():
    for vault,address in data.items():
        if vaultType=='yearnv4':
            vaults.append((vault+'v4',address))
        else:
            vaults.append((vault,address))
vaults = pd.DataFrame(vaults,columns={'vault','address'})
display(vaults.style.hide_index())